### ISSUE TITLE
Add readme for how to include code coverage in elixir

### ISSUE THREAD

**Issue by RobStallion** [dwyl/learn-elixir#105]
As a dev writing and testing elixir, I would like to be able to test code coverage to I can be sure that I have tested all functions in my application. 

- [x] Create a new mix project
- [x] Create some VERY simple functions
- [x] Add tests for these functions
- [x] Add travis build & codecov badges to Readme

**Comment by nelsonic** [comment]
@RobStallion thanks for doing this. 🥇 🎉
