### ISSUE TITLE
Contact pragprog.com to request volume license (bulk buy) Programming Elixir Book by Dave Thomas

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elixir#11]
The Elixir **Book**: https://pragprog.com/book/elixir13/programming-elixir-1-3
![Programming Elixir 1.3. front cover](https://cloud.githubusercontent.com/assets/194400/22402694/d13148de-e5f8-11e6-92cb-14584a353f7e.png)

is _easily_ the best way to learn Elixir. Should we consider buying 20 copies in "bulk" 
and _giving_ one to each person in DWYL to _accelerate_ people's learning?

![image](https://cloud.githubusercontent.com/assets/194400/22407638/45aed6fe-e662-11e6-8a31-2a5b2518a22f.png)

Who is _interested_ in getting a _paper_ copy of the book?

**Comment by SimonLab** [comment]
@nelsonic I think you already know that I'm interested by the book

**Comment by nelsonic** [comment]
@SimonLab noted. have sent them an email. let's see what they say. 👍

**Comment by nelsonic** [comment]
So... we emailed PragProg.com to request a discount for buying several books at once.
They got back to us with a "***20% Discount***... 
![prag-prog-no-discount](https://cloud.githubusercontent.com/assets/194400/22573978/ce093ec4-e9a3-11e6-86ed-caa06186fa5b.png)

The **_Recommended_ Retail Price** their website is for the Programming Phoenix book is: $34
https://pragprog.com/book/phoenix/programming-phoenix
![pragprog-phoenix-$34](https://cloud.githubusercontent.com/assets/194400/22574128/e9625f2e-e9a4-11e6-8a7c-e0a07c383b8b.png)
So the **"_discounted_" price** would be $34 - (0.2 x $34) = ***$27.20*** or ***£21.73***
https://www.wolframalpha.com/input/?i=$27.20+in+gbp
![image](https://cloud.githubusercontent.com/assets/194400/22574200/5a992ed4-e9a5-11e6-81ab-569f486baa9d.png)

Which is ***MORE EXPENSIVE THAN THE AMAZON RETAIL PRICE***!!!!!! 
**£21.34** at the time of writing:
https://www.amazon.co.uk/gp/product/1680501453/
![image](https://cloud.githubusercontent.com/assets/194400/22574252/b9db4a3a-e9a5-11e6-8dab-7ffe00b03638.png)

This ***literally*** Blows My Mind that a company would not _jump_ at the opportunity to sell their product **_directly_ to the customer** for a _lower_ price than the retailer and make ***more money*** overall because for Amazon to be selling them for £21.34, they _must_ be giving Amazon a decent discount, because Amazon is **NOT a Charity**!!

Then if we consider the offers on the Amazon Marketplace:
![programming-phoenix-cheaper-on-amazon-marketplace](https://cloud.githubusercontent.com/assets/194400/22574303/1ddd2954-e9a6-11e6-9bae-561ea9fab7a0.png)

It's ***pretty clear*** that "***Super Book Deals***" must be getting a pretty good price from PragProg in order to sell the book for **£13.87** ... 

So... ***obviously*** I placed an order from the Amazon Marketplace! (_cause I'm not an idiot with money to **burn**!!_) 
**Three** Phoenix Books:
![amazon-marketplace-phoenix-book](https://cloud.githubusercontent.com/assets/194400/22574658/23442ad0-e9a8-11e6-8c7f-438f690fe4c2.png)

**Two Elixir** Books:
![programming-elixir-2-copies](https://cloud.githubusercontent.com/assets/194400/22574721/919d0a10-e9a8-11e6-9e0f-b07aa56eb92c.png)


Prag Prog is still getting _paid_ for their ***Fantastic Content***. (_we aren't "stealing" it...!_)
But ... Rather than getting **£13.80 per book** (_what I proposed to Prag Prog..._) 
they will be getting what ever "**Super Book Deals**" is paying them ... i.e. ***considerably less***!!

> This my friends is how ***not*** to do business. 
Especially when there are ***so many*** people who are getting your content without paying... 
https://www.google.co.uk/search?q=programming%20phoenix%20pdf%20download%20free&rct=j
![image](https://cloud.githubusercontent.com/assets/194400/22574634/fe8bcd42-e9a7-11e6-9e75-5ab13d5abf2b.png)

**Comment by heru** [comment]
Hi..
I'm interested programming phoenix and programming elixir 1.3. Would you send me copies of books ?

Thanks you.

**Comment by nelsonic** [comment]
Hi Heru, 
Welcome to @dwyl! ❤️ 
We're stoked you want to learn elixir!
Have you had a look at http://elixirschool.com yet? (_how far did you get_?)
If you prefer to learn from a "book", please email me.
Thanks!
N :-)
