### ISSUE TITLE
Which Hex.pm Package for Parsing/Transforming Markdown to HTML?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elixir#112]
I need to parse Markdown and transform it to HTML which [hex.pm](https://hex.pm/) package  should I use?

## _Suggestions_ Welcome! 💬 

> **Note**: I have already done a _basic_ ("spike") of this, 
I'm opening the issue to _capture_ it in case it's _useful_ to someone `else`... 💭

**Comment by nelsonic** [comment]
In Club Soda we are using **`earmark`** https://hex.pm/packages/earmark 
https://github.com/club-soda/club-soda-guide/blob/a7d95752c3144cacbcce800d5420d9bd210e52a8/mix.exs#L53

Searching for "Markdown" on Hex.pm https://hex.pm/packages?search=markdown
It is the most _popular_ (_by downloads_) module for this purpose:
![image](https://user-images.githubusercontent.com/194400/52372701-bdb4be00-2a50-11e9-9e5f-a4decbae90f8.png)

Sorting for **_Total_ downloads** the popularity is _clear_ (_**10x** more than [**`edown`**](https://hex.pm/packages/edown)_)
https://hex.pm/packages?search=markdown&sort=total_downloads
![image](https://user-images.githubusercontent.com/194400/52372771-e2109a80-2a50-11e9-8c23-d8e116a16e1d.png)

## Anyone got _experience_ of using anything _other_ than `earmark`...?

**Comment by nelsonic** [comment]
Add `earmark` to the `deps` section of your `mix.exs` file:
```elixir
      { :earmark, "~> 1.3.0" }
```
example: https://github.com/nelsonic/nelsonic.github.io/blob/47e54c8d7dc93a5cac06795d1152ca0264f09b99/mix.exs#L22-L24

After running `mix deps.get` you will be able to transform `.md` into `.html`:

Code:
```elixir
  def transform do
    filename = Path.join(File.cwd!, "p/goals.md") # __ENV__.file # "./app.ex"
    # IO.puts filename
    case File.read(filename) do
      {:ok, markdown}      -> # do something with the `body`
        IO.puts markdown
        html_doc = Earmark.as_html!(markdown)
        IO.puts html_doc
        html_path = Path.join(File.cwd!, "p/goals.html")
        File.write!(html_path, html_doc)
      {:error, reason} -> # handle the error caused by `reason`
        IO.puts reason
    end
  end
```

**Comment by RobStallion** [comment]
@nelsonic I haven't used anything other than `earmar`k myself. I see that you ended up choosing `earmark` as well. I am just wondering if you looked into `edown` or any of the other options?

**Comment by nelsonic** [comment]
@RobStallion at the moment **`earmark`** meets my needs/requirements so I have not looked further.
My _actual_ work is to publish a Markdown file as HTML as _fast_ as possible.
As soon as I have **`new`** or more _advanced_ requirements I will investigate why **`edown`** exists ... https://hex.pm/packages/edown

Usually, when there is a "_competing_" package, it has _more_ or _better_ features.
Right now, I don't _need_ anything special, but anyone who has more advanced features should go for it.
