### ISSUE TITLE
Link to learn about test coverage is dead

### ISSUE THREAD

**Issue by Powerplex** [dwyl/learn-elixir#114]
The following link in the "Testing" section links to a 404: https://github.com/dwyl/learn-elixir/blob/master/codecov-example/codecov_example/README.md

**Comment by nelsonic** [comment]
@powerplex, thanks for opening this issue informing us. 👍🏻
The link should just be:
https://github.com/dwyl/learn-elixir/tree/master/codecov_example
If you have time, please create a pull request with the update/fix.
Thanks! 🙌
