### ISSUE TITLE
Clarify `function/<number of arguments>` notation in readme

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-elixir#132]
One of the first questions I had when I started reading books on elixir was around `function/<number of arguments>` notation. 

Most places just launch straight into it, including this readme in the [Truthiness section](https://github.com/dwyl/learn-elixir#truthiness-truthy-and-falsy-values):
![image](https://user-images.githubusercontent.com/4185328/64978828-4bda0800-d8ae-11e9-89ec-191277b86a0b.png)

I hadn't read it before and more recently I have heard other people raise the question on what it means.

It's super basic, but a one line clarification on this notation can help not break the flow for beginners.

**Comment by nelsonic** [comment]
https://culttt.com/2016/05/02/understanding-function-arity-elixir

**Comment by fusillicode** [comment]
Hi @iteles 😄

I took the liberty to add a few lines and a reference to the article suggested by @nelsonic.

If you want I can expand the few lines even more by adding a specific section under `Functions and Modules`.

Let me know 😄
