### ISSUE TITLE
Add link to example of description and package in `mix.exs` file?

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-elixir#137]
In the README we tell people to make sure their `mix.exs` files include a few things:
![image](https://user-images.githubusercontent.com/4185328/65372073-198c2a00-dc63-11e9-9413-3059565b2fe5.png)

But there is no example in this repo on how to do this.

Should we add a simple link to a couple of examples where this _is_ defined?
https://github.com/dwyl/cid/blob/master/mix.exs

**Comment by nelsonic** [comment]
Good plan. `cid` might be an "advanced" module to use as an example. but it's a good showcase. 👍
