### ISSUE TITLE
Mistake explanation of `chunk_every`?

### ISSUE THREAD

**Issue by kai-tub** [dwyl/learn-elixir#158]
The code uses [`chunk_every`](https://hexdocs.pm/elixir/Enum.html#chunk_every/2) which returns a list of lists with `n` elements per list. (The last chunk may contain fewer elements).

> It starts by converting and integer into a range which it then 'chunks' into a list of 4 lists (unless n < 4, in which case it just runs on a single process). The number 4 itself is not important, it could have been 5, 10 or 1000. What is important about it, is that it is the number of Processes we will be spawning. (Yes we could have spawned 1000 processes if we wanted to) [...]

So AFAIK, this block should be changed.
The number of lists/resulting processes will be `n % 4` if `n % 4 == 0` else `n % 4 + 1`.

Otherwise, thanks for the great introduction! :)

PS: I am happy to rewrite it and make a PR if you like.

**Comment by iteles** [comment]
Good catch. That would be grand @kai-tub, thanks!

**Comment by kai-tub** [comment]
One question, should we remove the code for fewer than 4 elements?

```elixir
  def spawn(n) when n < 4 do
    calc_product(n)
  end
```
I don't think there is any reason to keep the function, as `chunk_every` will just return a list containing a single list with fewer than 4 elements. Or do we want to change the number to something like 10 to show of the `when` keyword and argue that splitting creates more overhead?

**Comment by nelsonic** [comment]
Thanks again @kai-tub 🥇
