### ISSUE TITLE
YSR Aarogyasri Scheme

### ISSUE THREAD

**Issue by atozupdate1** [dwyl/learn-elixir#167]
YSR Aarogyasri is a health scheme introduced by the AP government. Andhra Pradesh Chief Minister Y.S.Jagan Mohan Reddy introduced this YSR Aarogyasri for poor people who can’t afford the costly medical bills. we are going to cover everything [how to download the health card](https://atozupdate.net/ysr-aarogyasri-scheme-apply-online/).

**Comment by nelsonic** [comment]
A great example of why GitHub needs better spam-blocking.
