### ISSUE TITLE
How To Login Hotmail account

### ISSUE THREAD

**Issue by logintutos789** [dwyl/learn-elixir#168]
Email is the most trusted and formal way of communication all over the world. With the development of innovative technology, many webmail services are available nowadays in the world of web. Traditionally, email used to the only source of communication through the internet back in the 90s. Here is the complete guide for [How To Sign up in Hotmail account](https://logintutos.com/hotmail-com-login-sign-up/).

**Comment by nelsonic** [comment]
this is why we can't have nice things ... 😕 

This spam/bot user joined 5 mins ago and was able to post this noise to a popular repository ...
![image](https://user-images.githubusercontent.com/194400/137120590-60cec324-87a6-4e2f-97ee-3f363882596a.png)

Obviously I've reported it to GitHub but it's just such a time-suck!
Who even _benefits_ from this crap?! 

![image](https://user-images.githubusercontent.com/194400/137120773-1561c38b-113e-405a-9687-43c86c73abde.png)

The bot (_whoever wrote it_) understands how create Markdown hyperlinks ... 
What even is `https://logintutos.com` ?! 🤷‍♂️ a pathetic attempt at Phishing people's Hotmail credentials.

Anyway. Closing. 🤦‍♂️
