### ISSUE TITLE
Background links section takes you away from tutorial

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-elixir#17]
The first two background links here are:
* [Introduction and Setup](http://elixir-lang.org/getting-started/introduction.html)
* [Getting started](http://elixir-lang.org/getting-started/basic-types.html)

If I'm minimally methodical about following the tutorial, these two links will take me into a separate world of learning about elixir *away* from the tutorial, the content of which is also part of the things that come next in the tutorial itself (installation, interactive mode and functional docs).

I would suggest that the two _interview_ links should be left in the background links section but that the two at the top of this issue are interspersed throughout the issue wherever it makes more sense (they are not background reading but the actual content of the tutorial).

**Comment by nelsonic** [comment]
Agreed. _please_ feel free to make the necessary updates/changes to improve it. ❤️
