### ISSUE TITLE
[Question] What is your process like when developing a package on Elixir?

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/learn-elixir#183]
As I'm starting my Elixir journey, I'm curious how more seasoned developers create and publish their own packages. I know there are [tons](https://dev.to/talk2megooseman/deploying-elixir-creating-your-own-elixir-package-58oh), and [tons](https://medium.com/kkempin/how-to-create-and-publish-hex-pm-package-elixir-90cb33e2592d) and [tons](https://inquisitivedeveloper.com/learn-with-me-elixir-application-packaging-63/) of resources out there.

But I'd like to know more about how developers usually **test** their packages as they implement their features. I've seen *three patterns* pop up:

- Creating a Phoenix boilerplate application (`mix phx.new`), duplicating the code as they go and testing the package within Phoenix.
- Running `iex -S mix` and testing their functions with mock parameters.
- Using TDD, creating tests beforehand and running their tests.
- Building the package and running it (like [so](https://inquisitivedeveloper.com/learn-with-me-elixir-application-packaging-63/))

I'm personally using a mix between the first and third option but I'm curious if there are any more advantageous or efficient ways of knowing your package won't break as soon as it's released 😛 .

**Comment by LuchoTurtle** [comment]
Closed due to #184 .
Thanks @nelsonic !

**Comment by nelsonic** [comment]
Anyone reading this in the future, the answer is: 
https://github.com/dwyl/learn-elixir/blob/main/code-reuse-hexpm.md
