### ISSUE TITLE
Try Elixir [online course]

### ISSUE THREAD

**Issue by gabrielperales** [dwyl/learn-elixir#27]
Codeschool just have released this course  https://www.codeschool.com/courses/try-elixir

**Comment by Cleop** [comment]
Thanks for sharing @gabrielperales. I'm currently learning Elixir so I'll give these a go and feedback on what I think.

**Comment by nelsonic** [comment]
![image](https://cloud.githubusercontent.com/assets/194400/23493665/6983dd0c-ff05-11e6-9d9d-8112bd103f51.png)

**Comment by gabrielperales** [comment]
That is great @nelsonic ! Right now i'm too busy with job and learning elm to start learning elixir also, but I want to do it sooner or later. I'm subscripted to codeschool newsletter, so I'm getting their updates, and the have released also [this elixir screencast](https://www.codeschool.com/screencasts/build-a-bank-statement-cli-application-with-elixir). I can't see it because I don't have a paid subscription at this moment, but I thought you may see it.

**Comment by Cleop** [comment]
I will add this section to the README now that I have finished watching the free videos and know what they cover.

**Comment by nelsonic** [comment]
@Cleop given that the course is not free/open beyond the "basics" I would limit to linking to the course so people are aware of it. I would much rather point people to: https://elixirschool.com which is 100% Free & Open Source. 👍

**Comment by Cleop** [comment]
Closing as the PR was merged in 👍
