### ISSUE TITLE
Syntax preferences

### ISSUE THREAD

**Issue by shouston3** [dwyl/learn-elixir#29]
What should be our syntax preference in these scenarios? Is it important?

### Strings
```elixir
String.contains "longer string" "string"
```

vs

```elixir
"longer string" =~ "string"
```

### Maps
```elixir
list = ~w(one two three)
```

vs

```elixir
list = ["one", "two", "three"]
```

**Comment by nelsonic** [comment]
if in doubt _always_ `expect` intelligent people to be "_lazy_". 
(_even though the more verbose version is quicker to read/maintain, it takes longer to write..._)
so go with the shorter version and just "up skill" the rest of the team. 😉

**Comment by shouston3** [comment]
Thanks @nelsonic, opting for `"longer string" =~ "string" and `~w(one two three)`
