### ISSUE TITLE
Edit README to be more concise and ordered more chronologically

### ISSUE THREAD

**Issue by Cleop** [dwyl/learn-elixir#30]
Currently the README is not far off 4000 words and from my own experience I found this, combined with the order in which topics are displayed/introduced a bit confusing when knowing where to start.

I am proposing to edit down the text a little (not to lose meaning but simply to make things more concise). As well as thinking about the order things appear, e.g. moving some of the longer video content which is about other topics such as phoenix lower down. It's not that this content isn't useful (hence not removing it), it's just that if you're trying to learn Elixir, you probably want to understand the basics of the language before you leap into phoenix.

I will make sure that people know that there is more content for them that may be of interest by making sure its included in the contents.

I think these changes could help improve people's learning experiences by helping them to learn the bits of elixir they need faster.

**Comment by nelsonic** [comment]
@Cleop some "editorial" on this repo would be _amazing_!! ❤️
