### ISSUE TITLE
Elixir School |> elixirschool.com |> Free/Open Source way to Learn Online

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elixir#33]
Web: http://elixirschool.com
GitHub: https://github.com/doomspork/elixir-school

**Comment by nelsonic** [comment]
Having _meticulously completed_ all lessons in Elixir School: https://github.com/nelsonic/practice/issues/10 
(_**don't open** that **link** on a **slow/mobile internet connection**! 
the issue contains screenshots of every step in Elixir School so it's **several MegaBytes**!!_)
I can confirm that the ["**Programming Elixir** Book](https://github.com/dwyl/learn-elixir/issues/11) is (["_night-and-day_"](https://english.stackexchange.com/a/144097/92019)) better and is **worth _every_ penny**.
The Elixir School (ES) lessons are _NOT_ (_complete_) beginner-friendly.
Many of the ES lessons compare an Elixir feature to something in Ruby/Java rather than _explaining_ it from first principals which requires further googling from the reader.
While the Lessons are organised in a reasonably logical order, none "_flow_" from the previous one. 
In the "Advanced" section, _often_ the instructions are _incomplete_ for where code should go e.g:
https://github.com/nelsonic/practice/issues/10#issuecomment-315594386 and given that there
are no link(s) to the _completed_ code it's difficult to debug/decipher. 

On the whole, I think there is a missed opportunity to build the _de facto_ Elixir learning resource.
I think we might have to _fill_ the gap in our own tutorial. 🤔

**Comment by YvesMuyaBenda** [comment]
Dilligence! @nelsonic Thanks for showing how your practice/learn. I wish more experienced developers would do this.
