### ISSUE TITLE
README.md is broken.

### ISSUE THREAD

**Issue by jruts** [dwyl/learn-elixir#38]
The README file is currently not rendering anymore.
It breaks down on line [630](https://github.com/dwyl/learn-elixir/blob/master/README.md#L629)

**Comment by nelsonic** [comment]
@jruts thanks for opening this issue _for_ the PR. 👍

**Comment by Cleop** [comment]
@jruts please can you close this issue now if you're happy it's been fixed?

**Comment by jruts** [comment]
I am always happy @Cleop :)

**Comment by nelsonic** [comment]
https://youtu.be/y6Sxv-sUYtM 🎵  🎧
