### ISSUE TITLE
Question: Try elixir level 2 ( Making function calls easier to read )

### ISSUE THREAD

**Issue by edwardcodes** [dwyl/learn-elixir#48]
Just finished the level 2 but i still have some doubts: 

**Exercise:**
```elixir
defmodule Person do
  def format_name(full_name) do
    format(String.split(full_name))
  end
end
```

**Solution:**
```elixir
defmodule Person do
  def format_name(full_name) do
    full_name
      |> String.split
      |> format
end
```

We use the pipe operator to clean up our code and to facilitate maintaining and reading the code (no doubts here) my question is:

Is there a correct order to "divide" a function using the pipe operator?

**Comment by edwardcodes** [comment]
![screen shot 2017-06-20 at 14 21 38](https://user-images.githubusercontent.com/8533973/27335308-ef906f04-55c3-11e7-8798-d3d59ce091bb.png)

**Comment by shouston3** [comment]
The order is important when you use the pipe operator.

In the **excercise** the functions are being called from right to left.

In the **solution** the functions are called from top to bottom.

**Comment by edwardcodes** [comment]
@shouston3 Thanks!

**Comment by iteles** [comment]
@edwardcodes Can we close this issue now? :)
