### ISSUE TITLE
Truthiness in Elixir

### ISSUE THREAD

**Issue by finnhodgkin** [dwyl/learn-elixir#61]
Currently there's no reference to truthiness in the readme. Given the prevalence of cond and conditional statements in Elixir I think think it would be good to add a reference to the top of `Basic types`. A few of the tutorials I followed at the start of my Elixir journey didn't talk about truthiness. It definitely negatively impacted my learning, especially coming from JS.

### Truthiness in Elixir

All values / types in Elixir apart from `nil` and `false` are truthy:

```ex
if 0 do "This is happening" end # "This is happening"

if "False" do "This is still happening" end # "This is still happening"

if false do "Not happening" end # nil
```

**Comment by finnhodgkin** [comment]
I'll make a preemptive PR. Feel free to ignore if you don't feel it's relevant :sparkles:

**Comment by finnhodgkin** [comment]
Closing this as the PR is merged :+1:

**Comment by nielsbom** [comment]
(old issue, I know)
I just created a PR for the official docs: https://github.com/elixir-lang/elixir/pull/8848
Maybe useful for dwyl too?

**Comment by nelsonic** [comment]
@nielsbom very useful. if you have time please mirror. thanks! 👍

**Comment by nielsbom** [comment]
See https://github.com/dwyl/learn-elixir/pull/121

(I will not pollute this issue any more 🙂)

**Comment by nelsonic** [comment]
Years later while pairing with someone who has never used `Elixir`. 🧑‍💻 
They Googled for "_elixir truthy falsy_" and this issue was on the first page! 🤯 
Thanks for opening this issue Finn & thanks for addressing it Niels. ❤️ 🖖

**Comment by nielsbom** [comment]
You're welcome :-)

Nice to get a message like this on a Monday morning.

Stay cool 😎

**Comment by nelsonic** [comment]
@nielsbom I know right?! 🙌 
It's so cool when you find things useful half a decade later! 🎉 

The `Elixir` beginner knew immediately that `0` (integer) is not `falsy` in elixir. 

The obvious way to check is `IEx`:
```elixir
if 0, do: IO.puts("0 is truthy"), else: IO.puts("0 is falsy")
0 is truthy
:ok
```
But the person in question didn't know they can use `IEx` to "_Ask_ the computer" (without Google!)

Anyway, hope you are well and have a great week. ☀️
