### ISSUE TITLE
Difference between tuples and lists

### ISSUE THREAD

**Issue by JMurphyWeb** [dwyl/learn-elixir#7]
According to the readme: 
> Tuples are similar to lists except the items are stored in order

Which suggests that items in a list are not stored in order.

**Comment by nelsonic** [comment]
@JMurphyWeb thanks for helping to _clarify_ that. please close the issue if you feel it's "_fixed_"! thanks! ❤️

**Comment by JMurphyWeb** [comment]
I think is about as clear as it is my mind...
